name: JetBrains Github Publish
on:
  push:
    branches:
      - test-754
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        version: [21]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: ${{ matrix.version }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
      - name: Build with Gradle
        run: gradle build

      - name: Publish to GitHub Packages
        run: gradle publish
        env:
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
